default:
  image: docker:latest

stages:

- build





build:

  stage: build

  before_script:
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - cat $HOME/.docker/config.json

  script:
    - apk add curl
    - apk add git
    

    - curl -sSL https://cli.openfaas.com |  sh

    - docker login docker.io  --username gaithmtiri --password OnePiece9816*
    - faas-cli build -f helloo.yml
    #- faas-cli push -f helloo.yml

  

