default:
  image: docker:latest

stages:

- build


build:

  stage: build

  before_script:
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - docker login -u "gaithmtiri" -p "OnePiece9816*"

  script:
    - apk add curl
    - apk add git
    - echo "YOO"
    - docker status
    

    # - curl -sSL https://cli.openfaas.com |  sh

    # - docker login https://index.docker.io/v1/  --username gaithmtiri --password OnePiece9816*
    # - faas-cli build -f helloo.yml
    #- faas-cli push -f helloo.yml

  

