docker-build:
  stage: build

  image:
    name: docker:stable
  services:
   - name: docker:dind
     alias: thedockerhost
     entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - apk add curl
    - apk add git
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    

    # - curl -sSL https://cli.openfaas.com |  sh

    # # - docker login --username gaithmtiri --password OnePiece9816* https://index.docker.io/v1/
    # - faas-cli build -f helloo.yml
    # - faas-cli push -f helloo.yml

  

