docker-build:
  stage: build

  image:
    name: docker:stable
  services:
   - name: docker:dind
     alias: thedockerhost
     entrypoint: ["dockerd-entrypoint.sh", "--tls=false","--insecure-registry=registry:5000"]

  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - sleep 360
    - apk add --no-cache git
    - if [ -f "./faas-cli" ] ; then cp ./faas-cli /usr/local/bin/faas-cli || 0 ; fi
    - if [ ! -f "/usr/local/bin/faas-cli" ] ; then apk add --no-cache curl git && curl -sSL cli.openfaas.com | sh && chmod +x /usr/local/bin/faas-cli && /usr/local/bin/faas-cli template pull && cp /usr/local/bin/faas-cli ./faas-cli ; fi

    # Build Docker image
    - /usr/local/bin/faas-cli build --tag=sha --parallel=2 -f helloo.yml

    # Login & Push Docker image to private repo
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - /usr/local/bin/faas-cli push --tag=sha -f helloo.yml



    # - apk add curl
    # - apk add git
    # - echo $CI_REGISTRY
    
    

    # - curl -sSL https://cli.openfaas.com |  sh

    # # # - docker login --username gaithmtiri --password OnePiece9816* https://index.docker.io/v1/
    # - faas-cli build -f helloo.yml
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # # - faas-cli login --username root --password toortoor --server http://registry:5000
    # - faas-cli push -f helloo.yml

  

