default:
  image: docker:latest

stages:

- build





build:

  stage: build

  script:
    - apk add curl

    - curl -sSL https://cli.openfaas.com |  sh
    - echo $CI_REGISTRY

    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - faas-cli build -f helloo.yml
    - faas-cli push -f helloo.yml

  

