default:
  image: docker:latest

stages:

- build





build:

  stage: build

  script:
    - apk add curl

    - curl -sSL https://cli.openfaas.com |  sh

    - docker login --username gaithmtiri --password OnePiece9816* docker.io
    - faas-cli build -f helloo.yml
    - faas-cli push -f helloo.yml

  

