default:
  image: docker:latest

stages:

- build





build:

  stage: build

  before_script:
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - cat $HOME/.docker/config.json
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - apk add curl
    - apk add git
    

    - curl -sSL https://cli.openfaas.com |  sh

    # - docker login https://index.docker.io/v1/  --username gaithmtiri --password OnePiece9816*
    - faas-cli build -f helloo.yml
    #- faas-cli push -f helloo.yml

  

