default:
  image: docker:latest

stages:

- build





build:

  stage: build

  before_script:
  - mkdir -p $HOME/.docker
  - eval $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

  script:
    - apk add curl
    - apk add git

    - curl -sSL https://cli.openfaas.com |  sh

    #- docker login --username gaithmtiri --password OnePiece9816* docker.io
    - faas-cli build -f helloo.yml
    #- faas-cli push -f helloo.yml

  

